### ISSUE TITLE
[Question] How do I open/modify the MessagePack files?

### ISSUE THREAD

**Issue by AlbertCoolGuy** [3DStris/3DStris#100]

**Comment by geniiii** [comment]
I'm not actually sure.. Maybe there are some editors for the format. It's not exactly designed to be edited by users. I usually use a hex editor to change the values manually, but that's not the most user-friendly method.

**Comment by AlbertCoolGuy** [comment]
I found something https://iot-dsa-v2.github.io/msgpack-editor/
