### ISSUE TITLE
Opening the scoreboard freezes the system for over a minute

### ISSUE THREAD

**Issue by Still34** [3DStris/3DStris#115]
No crash dump, tested on a New 3DS hardware. The entire console straight up freezes for at least a minute before the scoreboard could be opened. I have 121+ games scored.

**Comment by geniiii** [comment]
That's pretty bad, even with thousands of games it didn't take that long when I last tested. Perhaps it's the multithreading screwing up somehow? Could you attach your `games.mp` file? (located in `sdmc:/3ds/3dstris/`)

**Comment by Still34** [comment]
Sure, here it is https://send.firefox.com/download/fe50d3364bc81cb0/#VKdwk9uJtO9xamQMTd6UzQ

**Comment by geniiii** [comment]
I can't seem to replicate this issue (on an old 3DS), I'll make a custom build which logs related info soon.
