### ISSUE TITLE
Odd grid drawing on real hardware

### ISSUE THREAD

**Issue by geniiii** [3DStris/3DStris#120]
Regression from f93df87dade1ca5fc7d1705f4ee337dc95e73bf8

**Comment by geniiii** [comment]
Citra:
![image](https://user-images.githubusercontent.com/24881499/84250174-60cd8a00-ab14-11ea-9c11-cd8be31cda38.png)
Real HW (o3DS):
![broken](https://user-images.githubusercontent.com/24881499/84250479-c6217b00-ab14-11ea-8108-534d3e7d51d8.png)

**Comment by Still34** [comment]
Can confirm on New 3DS as well.

**Comment by geniiii** [comment]
Fixed by db343691285613057802f211be60d9d3e953c810
