### ISSUE TITLE
[Question] How can I translate 3DStris to danish?

### ISSUE THREAD

**Issue by AlbertCoolGuy** [3DStris/3DStris#97]
I wanna translate 3DStris to danish.

**Comment by geniiii** [comment]
I have been thinking of adding Crowdin support, but haven't gotten around to it yet. For now, you could fork the project, copy, rename and modify `data/romfs/lang/en.json`, then make a pull request. I can do the code changes.

**Comment by AlbertCoolGuy** [comment]
Thanks!
