### ISSUE TITLE
Weblate support

### ISSUE THREAD

**Issue by geniiii** [3DStris/3DStris#99]

**Comment by comradekingu** [comment]
@geniiii Why Crowdin and not Weblate?
As a translator I can't see any reason to do so. It is also closed source vs libre software, user tracking vs no user tracking. Need to be non-commercial and contribute to the TM to qualify for gratis libre software hosting vs gratis for libre software hosting.
I'll make a nb_NO translation if I see it on Hosted Weblate or elsewhere. :)
I have a 3DS with a flashcart, I was sad when Nintendo shut down the servers for multiplayer for Tetris on the Original DS/DSi, so nice to see this.

**Comment by geniiii** [comment]
Yes, a FLOSS option is indeed much better. The reason I picked Crowdin was purely ignorance, I didn't really look into any alternatives.
Thank you!

**Comment by geniiii** [comment]
Update: Applied for hosting on Hosted Weblate, relevant code changes have been made in #106.

**Comment by geniiii** [comment]
Approved, https://hosted.weblate.org/projects/3dstris
